In [3]:
import numpy as np

In [4]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [5]:
print(a[0])

[1 2 3 4]


In [6]:
print(a[1])

[5 6 7 8]


In [7]:
print(a[2])

[ 9 10 11 12]


In [8]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [10]:
np.empty(6)

array([0., 0., 0., 0., 0., 0.])

In [11]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [3]:
np.arange(2,29,5)

array([ 2,  7, 12, 17, 22, 27])

In [8]:
arr = np.array([1,2,3,4,5,6,7,8])

In [5]:
np.append(arr,[9,10])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
np.delete(arr,[1])

array([1, 3, 4, 5, 6, 7, 8])

In [10]:
arr = np.array([3,7,5,1])
np.sort(arr)

array([1, 3, 5, 7])

In [11]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]]])

print(array_example)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [12]:
array_example.ndim

3

In [13]:
array_example.size

24

In [14]:
array_example.shape

(3, 2, 4)

In [15]:
arr_one = np.array([[1, 2, 3, 4, 5]])

In [16]:
arr_one.ndim

2

In [17]:
arr_one.size

5

In [18]:
arr_one.shape

(1, 5)

In [19]:
a = np.arange(6)

In [20]:
a

array([0, 1, 2, 3, 4, 5])

In [21]:
b = a.reshape(3,2)

In [22]:
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [24]:
b = a.reshape(6,1)

In [25]:
b

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [30]:
a = np.array([1, 2, 3, 4, 5, 6])

In [31]:
a.shape

(6,)

In [32]:
a.size

6

In [33]:
a.ndim

1

In [34]:
a2 = a[np.newaxis]
print(a2.shape)
print(a2)

(1, 6)
[[1 2 3 4 5 6]]


In [35]:
row_vector = a[np.newaxis, :]
print(row_vector.shape)
print(row_vector)

(1, 6)
[[1 2 3 4 5 6]]


In [36]:
col_vector = a[:,np.newaxis]
print(col_vector.shape)
print(col_vector)

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [37]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [38]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [39]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

In [40]:
data = np.array([1,2,3])

print(data)
print(data[0])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

[1 2 3]
1
2
[1 2]
[2 3]
[2 3]


In [41]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [42]:
a.ndim

2

In [43]:
a.size

12

In [44]:
a.shape

(3, 4)

In [45]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [46]:
print(a[a>=5])

[ 5  6  7  8  9 10 11 12]


In [47]:
five_up = (a >= 5)
print(a[five_up])
print(a[a >=5])

[ 5  6  7  8  9 10 11 12]
[ 5  6  7  8  9 10 11 12]


In [48]:
divisible_2 = a[a%2==0]
print(divisible_2)

[ 2  4  6  8 10 12]


In [49]:
c = a[(a > 2) & (a < 11)]

print(c)

[ 3  4  5  6  7  8  9 10]


In [50]:
arr = np.array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [51]:
arr1 = arr[3:8]
arr1

array([4, 5, 6, 7, 8])

In [67]:
a_1 = np.array([[1, 1],
                [2, 2]])
a_2 = np.array([[3, 3],
                [4, 4]])


In [70]:
a_3

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [71]:
a_1

array([[1, 1],
       [2, 2]])

In [72]:
a_2

array([[3, 3],
       [4, 4]])

In [74]:
a_3

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [76]:
np.delete(a_3, 1)

array([1, 2, 2, 3, 3, 4, 4])

In [80]:
a_3

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [81]:
b_1 = np.array([[1, 1],
                [2, 2]])

In [82]:
b_2 = np.array([[3, 3],
                [4, 4]])

In [83]:
np.hstack((b_1, b_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [84]:
arrsplit = np.array([[1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
                     [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

print(arrsplit)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [88]:
print(arrsplit.ndim)
print(arrsplit.size)
print(arrsplit.shape)

2
24
(2, 12)


In [90]:
pecah = np.hsplit(arrsplit, 3)
pecah

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [93]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [94]:
b = a.view()
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [95]:
c = a.copy()
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [96]:
a = np.array([1, 2, 3, 4])

# Add all of the elements in the array
a.sum()

10

In [97]:
b = np.array([[1, 1], [2, 2]])
b

array([[1, 1],
       [2, 2]])

In [98]:
b.sum(axis=0)

array([3, 3])

In [99]:
b.sum(axis = 1)

array([2, 4])

In [100]:
data = np.array([1, 2])
data

array([1, 2])

In [101]:
ones = np.ones(2)
ones

array([1., 1.])

In [102]:
data + ones

array([2., 3.])

In [103]:
data * data

array([1, 4])

In [104]:
data / data

array([1., 1.])

In [105]:
data * 2

array([2, 4])

In [106]:
A = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

print(A)

[[0.45053314 0.17296777 0.34376245 0.5510652 ]
 [0.54627315 0.05093587 0.40067661 0.55645993]
 [0.12697628 0.82485143 0.26590556 0.56917101]]


In [107]:
A.sum()

4.8595784

In [108]:
A.min()

0.05093587

In [109]:
A.min(axis=0)


array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [110]:
A.max()

0.82485143

In [111]:
A.max(axis=1)

array([0.5510652 , 0.55645993, 0.82485143])

In [112]:
A.std()

0.21392120766089617

In [113]:
print(np.ones((3,2)))
print(np.zeros((3,2)))
print(np.random.random((3,2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[0.93844132 0.41432265]
 [0.9724963  0.93816398]
 [0.649728   0.23649332]]


In [4]:
data = np.array([[1, 2], [3, 4]])
print(data)

[[1 2]
 [3 4]]


In [5]:
ones = np.ones([2,2])

In [6]:
print(ones)

[[1. 1.]
 [1. 1.]]


In [7]:
print(data + ones)

[[2. 3.]
 [4. 5.]]


In [8]:
ones_row = np.ones([1,2])

In [9]:
print(ones_row)

[[1. 1.]]


In [10]:
print(data + ones_row)

[[2. 3.]
 [4. 5.]]


In [11]:
data

array([[1, 2],
       [3, 4]])

In [12]:
ones_row

array([[1., 1.]])

In [13]:
data + ones_row

array([[2., 3.],
       [4., 5.]])

In [15]:
a_1 = np.array([[1,2,3],[4,5,6]])
print(a_1)
print(a_1.shape)

a_2 = np.array([[7,8],[9,10],[11,12]])
print(a_2)
print(a_2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[ 7  8]
 [ 9 10]
 [11 12]]
(3, 2)


In [16]:
np.dot(a_1, a_2)

array([[ 58,  64],
       [139, 154]])

In [23]:
data = np.array([[1, 2], [3, 4], [5, 6]])

print(data)
print('waw')
print(data[0])
print('waw')
print(data[1])
print('waw')
print(data[2])
print('waw')
print(data[0,1])
print('waw')
print(data[1:3])
print('waw')
print(data[0:2,1])

[[1 2]
 [3 4]
 [5 6]]
waw
[1 2]
waw
[3 4]
waw
[5 6]
waw
2
waw
[[3 4]
 [5 6]]
waw
[2 4]


In [24]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [25]:
print(data.max())
print(data.min())
print(data.sum())

6
1
21


In [28]:
print(data.max(axis = 0))
print(data.max(axis = 1))

[5 6]
[2 4 6]


In [29]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [30]:
print(data.T)

[[1 3 5]
 [2 4 6]]


In [31]:
data_col = np.array([[1, 2, 3, 4, 5, 6]]).T
print(data_col)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [33]:
data_col.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
data_col.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [35]:
arr = np.arange(6).reshape((2, 3))
print(arr)

[[0 1 2]
 [3 4 5]]


In [36]:
ndarr = np.array([[[1, 2], [3, 4]],
                  [[5, 6], [7, 8]]])

print(ndarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [39]:
print(np.ones((4,3,2)))

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [40]:
print(np.zeros((4,3,2)))

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [41]:
print(np.random.random((4,3,2)))

[[[0.14064982 0.87836564]
  [0.18410184 0.51304981]
  [0.8701881  0.50278373]]

 [[0.96673179 0.26019853]
  [0.1799601  0.06594579]
  [0.06113031 0.00525745]]

 [[0.77607711 0.6541921 ]
  [0.07355968 0.22305309]
  [0.41870125 0.17721262]]

 [[0.70663446 0.51499829]
  [0.83940667 0.54451117]
  [0.9980554  0.35340801]]]


In [42]:
arrflat = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print(arrflat)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [43]:
arrflat.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])