# SESSION 9

In [137]:
import math
import statistics
import numpy as np
import scipy.stats
import pandas as pd
import matplotlib.pyplot as plt
plt.style.use('ggplot')

In [2]:
x = [8.0, 1, 2.5, 4, 28.0]
x_with_nan = [8.0, 1, 2.5, math.nan, 4, 28.0]
print(x)
print(x_with_nan)

[8.0, 1, 2.5, 4, 28.0]
[8.0, 1, 2.5, nan, 4, 28.0]


In [3]:
y, y_with_nan = np.array(x), np.array(x_with_nan)
z, z_with_nan = pd.Series(x), pd.Series(x_with_nan)
print(y)
print(y_with_nan)
print(z_with_nan)

[ 8.   1.   2.5  4.  28. ]
[ 8.   1.   2.5  nan  4.  28. ]
0     8.0
1     1.0
2     2.5
3     NaN
4     4.0
5    28.0
dtype: float64


In [4]:
mean_ = sum(x) / len(x)
mean_

8.7

In [6]:
mean_ = statistics.mean(x)
print(mean_)

8.7


In [7]:
mean_ = statistics.mean(x_with_nan)
print(mean_)

nan


In [8]:
mean_ = np.mean(y)
mean_

8.7

In [9]:
mean_ = y.mean()
mean_

8.7

In [10]:
print(np.mean(y_with_nan))
print(y_with_nan.mean())

nan
nan


In [11]:
np.nanmean(y_with_nan)

8.7

In [12]:
mean_ = z.mean()
mean_

8.7

In [13]:
z_with_nan.mean()

8.7

In [14]:
x = [8.0, 1, 2.5, 4, 28.0]
w = [0.1, 0.2, 0.3, 0.25, 0.15]

wmean = sum(w[i] * x[i] for i in range(len(x))) / sum(w)
print(wmean)

wmean = sum(x_ * w_ for (x_, w_) in zip(x, w)) / sum(w)
print(wmean)

6.95
6.95


In [15]:
y, z, w = np.array(x), pd.Series(x), np.array(w)

wmean = np.average(y, weights=w)
print(wmean)

wmean = np.average(z, weights=w)
print(wmean)

6.95
6.95


In [21]:
y.shape

(5,)

In [22]:
(w * y).sum() / w.sum()

6.95

In [23]:
w.shape

(5,)

In [24]:
y.shape

(5,)

In [25]:
hmean = len(x) / sum(1 / item for item in x)
hmean

2.7613412228796843

In [26]:
hmean = statistics.harmonic_mean(x)
hmean

2.7613412228796843

In [27]:
scipy.stats.hmean(y)

2.7613412228796843

In [28]:
scipy.stats.hmean(z)

2.7613412228796843

In [29]:
gmean = 1

for item in x:
    gmean *= item

gmean **= 1 / len(x)
gmean

4.677885674856041

In [30]:
scipy.stats.gmean(y)

4.67788567485604

In [31]:
scipy.stats.gmean(z)

4.67788567485604

In [32]:
n = len(x)
if n % 2:
    median_ = sorted(x)[round(0.5*(n-1))]
else:
    x_ord, index = sorted(x), round(0.5 * n)
    median_ = 0.5 * (x_ord[index-1] + x_ord[index])

median_

4

In [33]:
x

[8.0, 1, 2.5, 4, 28.0]

In [35]:
statistics.median_low(x[:-1])

2.5

In [36]:
statistics.median_high(x[:-1])

4

In [37]:
print(statistics.median(x_with_nan))
print(statistics.median_low(x_with_nan))
print(statistics.median_high(x_with_nan))

6.0
4
8.0


In [38]:
median_ = np.median(y)
print(median_)

4.0


In [39]:
median_ = np.median(y[:-1])
print(median_)

3.25


In [40]:
u = [2, 3, 2, 8, 12]

v = [12, 15, 12, 15, 21, 15, 12]

mode_ = max((u.count(item), item) for item in set(u))[1]
mode_

2

In [41]:
mode_ = statistics.mode(u)
mode_

2

In [42]:
u, v = np.array(u), np.array(v)

mode_ = scipy.stats.mode(u)
mode_

ModeResult(mode=array([2]), count=array([2]))

In [43]:
mode_ = scipy.stats.mode(v)
mode_

ModeResult(mode=array([12]), count=array([3]))

In [44]:
print(mode_.mode)
print(mode_.count)

[12]
[3]


In [45]:
u, v, w = pd.Series(u), pd.Series(v), pd.Series([2, 2, math.nan])

print(u.mode())

print(v.mode())

print(w.mode())

0    2
dtype: int64
0    12
1    15
dtype: int64
0    2.0
dtype: float64


In [46]:
n = len(x)

mean_ = sum(x) / n

var_ = sum((item - mean_)**2 for item in x) / (n - 1)
var_

123.19999999999999

In [47]:
var_ = statistics.variance(x)
var_

123.2

In [48]:
var_ = np.var(y, ddof=1)
var_

123.19999999999999

In [49]:
var_ = y.var(ddof=1)
var_

123.19999999999999

In [50]:
z.var(ddof=1)

123.19999999999999

In [52]:
std_ = var_ ** 0.5
std_

11.099549540409285

In [53]:
std_ = statistics.stdev(x)
std_

11.099549540409287

In [54]:
np.std(y, ddof=1)

11.099549540409285

In [55]:
y.std(ddof=1)

11.099549540409285

In [56]:
z.std(ddof=1)

11.099549540409285

In [57]:
x = [8.0, 1, 2.5, 4, 28.0]

n = len(x)

mean_ = sum(x) / n
var_ = sum((item - mean_)**2 for item in x) / (n-1)
std_ = var_ ** 0.5

skew_ = (sum((item - mean_)**3 for item in x) * n / ((n - 1) * (n - 2) * std_**3))

In [58]:
skew_

1.9470432273905929

In [59]:
y, y_with_nan = np.array(x), np.array(x_with_nan)

scipy.stats.skew(y, bias=False)

1.9470432273905927

In [60]:
scipy.stats.skew(y_with_nan, bias=False)

nan

In [61]:
z, z_with_nan = pd.Series(x), pd.Series(x_with_nan)

z.skew()

1.9470432273905924

In [62]:
z_with_nan.skew()

1.9470432273905924

In [63]:
>>> x = [-5.0, -1.1, 0.1, 2.0, 8.0, 12.8, 21.0, 25.8, 41.0]
>>> statistics.quantiles(x, n=2)
[8.0]
>>> statistics.quantiles(x, n=4, method='inclusive')
[0.1, 8.0, 21.0]

[0.1, 8.0, 21.0]

In [64]:
>>> y = np.array(x)
>>> np.percentile(y, 5)
-3.44
>>> np.percentile(y, 95)
34.919999999999995

34.919999999999995

In [67]:
np.percentile(y, [25, 50, 75])

array([ 0.1,  8. , 21. ])

In [68]:
np.median(y)

8.0

In [69]:
y_with_nan = np.insert(y, 2, np.nan)

In [70]:
y_with_nan

array([-5. , -1.1,  nan,  0.1,  2. ,  8. , 12.8, 21. , 25.8, 41. ])

In [71]:
np.nanpercentile(y_with_nan, [25, 50, 75])

array([ 0.1,  8. , 21. ])

In [72]:
np.quantile(y, 0.05)

-3.44

In [73]:
np.quantile(y, 0.95)

34.919999999999995

In [74]:
np.quantile(y, [0.25, 0.5, 0.75])

array([ 0.1,  8. , 21. ])

In [75]:
np.nanquantile(y_with_nan, [0.25, 0.5, 0.75])

array([ 0.1,  8. , 21. ])

In [76]:
z, z_with_nan = pd.Series(y), pd.Series(y_with_nan)

In [77]:
z.quantile(0.05)

-3.44

In [78]:
z.quantile(0.95)

34.919999999999995

In [80]:
z.quantile([0.25, 0.5, 0.75])

0.25     0.1
0.50     8.0
0.75    21.0
dtype: float64

In [81]:
z_with_nan.quantile([0.25, 0.5, 0.75])

0.25     0.1
0.50     8.0
0.75    21.0
dtype: float64

In [82]:
np.ptp(y)

46.0

In [83]:
np.ptp(z)

46.0

In [84]:
np.ptp(y_with_nan)

nan

In [85]:
np.ptp(z_with_nan)

nan

In [86]:
quartiles = np.quantile(y, [0.25, 0.75])

In [87]:
quartiles[1] - quartiles[0]

20.9

In [88]:
quartiles = z.quantile([0.25, 0.75])

In [89]:
quartiles[0.75] - quartiles[0.25]

20.9

In [90]:
result = scipy.stats.describe(y, ddof=1, bias=False)

In [91]:
result

DescribeResult(nobs=9, minmax=(-5.0, 41.0), mean=11.622222222222222, variance=228.75194444444446, skewness=0.9249043136685094, kurtosis=0.14770623629658886)

In [92]:
x = list(range(-10, 11))

In [93]:
y = [0, 2, 2, 2, 2, 3, 3, 6, 7, 4, 7, 6, 6, 9, 4, 5, 5, 10, 11, 12, 14]

In [94]:
x_, y_ = np.array(x), np.array(y)

In [95]:
x__, y__ = pd.Series(x_), pd.Series(y_)

In [96]:
n = len(x)

In [97]:
mean_x, mean_y = sum(x) / n, sum(y) / n

In [99]:
cov_xy = (sum((x[k] - mean_x) * (y[k] - mean_y) for k in range(n)) / (n - 1))

In [100]:
cov_xy

19.95

In [101]:
cov_matrix = np.cov(x_, y_)

In [102]:
cov_matrix

array([[38.5       , 19.95      ],
       [19.95      , 13.91428571]])

In [103]:
x_.var(ddof=1)

38.5

In [104]:
y_.var(ddof=1)

13.914285714285711

In [105]:
cov_xy = cov_matrix[0, 1]

In [106]:
cov_xy

19.950000000000003

In [107]:
cov_xy = cov_matrix[1, 0]

In [108]:
cov_xy

19.950000000000003

In [109]:
cov_xy = x__.cov(y__)

In [110]:
cov_xy

19.950000000000003

In [111]:
cov_xy = y__.cov(x__)

In [112]:
cov_xy

19.950000000000003

In [113]:
var_x = sum((item - mean_x)**2 for item in x) / (n - 1)

In [114]:
var_y = sum((item - mean_y)**2 for item in y) / (n - 1)

In [115]:
std_x, std_y = var_x ** 0.5, var_y ** 0.5

In [116]:
 r = cov_xy / (std_x * std_y)

In [117]:
r

0.8619500056316062

In [118]:
r, p = scipy.stats.pearsonr(x_, y_)

In [119]:
r

0.8619500056316061

In [120]:
p

5.122760847201135e-07

In [121]:
corr_matrix = np.corrcoef(x_, y_)

In [122]:
corr_matrix

array([[1.        , 0.86195001],
       [0.86195001, 1.        ]])

In [124]:
r = corr_matrix[0, 1]

In [125]:
r

0.8619500056316062

In [126]:
r = corr_matrix[1, 0]

In [127]:
r

0.8619500056316062

In [128]:
scipy.stats.linregress(x_, y_)

LinregressResult(slope=0.5181818181818182, intercept=5.714285714285714, rvalue=0.8619500056316061, pvalue=5.122760847201128e-07, stderr=0.06992387660074978, intercept_stderr=0.42341009950025876)

In [129]:
result = scipy.stats.linregress(x_, y_)

In [130]:
r = result.rvalue

In [131]:
r

0.8619500056316061

In [132]:
r = x__.corr(y__)

In [133]:
r

0.8619500056316062

In [134]:
r = y__.corr(x__)

In [135]:
r

0.8619500056316062