In [54]:
def soal1():
    import numpy as np
    mulai = int (input('Mulai :'))
    selesai = int (input('Selesai :'))
    print('1 dimensi')
    dimension_1 = np.arange(mulai, selesai)
    jumlah = int(len(dimension_1))
    print(dimension_1)
    print('2 dimensi')
    dimension_2 = dimension_1.reshape(3,int(jumlah/3))
    print(dimension_2)
    dimension_3 = dimension_2.reshape(3,3,3)
    print('3 dimensi')
    print(dimension_3)
    return;

In [77]:
soal1()

Mulai :1
Selesai :28
1 dimensi
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27]
2 dimensi
[[ 1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18]
 [19 20 21 22 23 24 25 26 27]]
3 dimensi
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [81]:

def Soal2():
    import random
    Input = int(input('Banyak Data :'))
    mulai = int(input('Mulai angka :'))
    selesai = int(input('Selesai angka :'))
    #Bikin list integer random dari inputan
    intlist = []
    for x in range(Input):
        n = random.randint(mulai, selesai)
        intlist.append(n)

    arrlist = np.array(intlist)
    print('1 dimensi random')
    print(arrlist)
    print('2 dimensi')
    dimensi_2 = arrlist.reshape(4,4)
    print(dimensi_2)
    print('ini dibalik 2 dimensi')
    dimensi_2_balik = dimensi_2[:,::-1]
    print(dimensi_2_balik)
    return;


In [83]:
Soal2()

Banyak Data :16
Mulai angka :1
Selesai angka :50
1 dimensi random
[ 8 20 16 36 31 41  5 19 23 46 46 44  3 42 42 29]
2 dimensi
[[ 8 20 16 36]
 [31 41  5 19]
 [23 46 46 44]
 [ 3 42 42 29]]
ini dibalik 2 dimensi
[[36 16 20  8]
 [19  5 41 31]
 [44 46 46 23]
 [29 42 42  3]]


In [109]:
x=np.ones((10,10))*4
#print(x)
x[1:-1,1:-1]=0
#x[1:9,1:9]
x

array([[4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.]])